version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "5173:5173" # Vite default port
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev # Vite dev command
